# Generated by Django 4.1.7 on 2023-03-14 01:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorpHistoricalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='corp name')),
                ('ticker', models.CharField(max_length=30, verbose_name='corp ticker')),
                ('open', models.IntegerField()),
                ('high', models.IntegerField()),
                ('low', models.IntegerField()),
                ('close', models.IntegerField()),
                ('volumn', models.IntegerField()),
                ('date', models.DateField(default=datetime.datetime(2023, 3, 14, 1, 32, 42, 372606, tzinfo=datetime.timezone.utc))),
            ],
            options={
                'db_table': 'corp_historical_table',
            },
        ),
    ]
